development:
  database: travis_development
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  database: travis_production
  adapter: postgresql
  encoding: unicode
  pool: 5

jasmine:
  database: travis_jasmine
  adapter: postgresql
  encoding: unicode
  pool: 5

test: &test
  database: travis_test
  adapter: postgresql
  encoding: unicode
  pool: 5

  database: travis_test
  adapter: postgresql
  encoding: unicode
  pool: 5

